### ISSUE TITLE
Unnecessary list comprehension usage

### ISSUE THREAD

**Issue by VIVALDI142857** [SENATOROVAI/pre-commit#1]
So if we try to use list comprehension as we are supposed to do to complete practice part in 8th chapter of python made easy book, it'll raise a mistake about its irrelevant usage.
<img width="645" alt="Снимок экрана 2024-10-14 в 21 53 38" src="https://github.com/user-attachments/assets/21ec1784-6a5e-4cb9-9f98-37e9232cbe3c">
<img width="1116" alt="Снимок экрана 2024-10-14 в 21 54 50" src="https://github.com/user-attachments/assets/5df09665-b60c-431d-91f9-df11e6adeae0">

**Comment by ruslansenatorov** [comment]
send the file with the error here

**Comment by VIVALDI142857** [comment]
[chapter_11_classes_python_made_easy.json](https://github.com/user-attachments/files/17513542/chapter_11_classes_python_made_easy.json)
Here it is

**Comment by ruslansenatorov** [comment]
> [chapter_11_classes_python_made_easy.json](https://github.com/user-attachments/files/17513542/chapter_11_classes_python_made_easy.json) Here it is

https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/unnecessary-comprehension.html

**Comment by ruslansenatorov** [comment]
> [chapter_11_classes_python_made_easy.json](https://github.com/user-attachments/files/17513542/chapter_11_classes_python_made_easy.json) Here it is

НАЗВАНИЕ ИШЬЮСА НЕ ПО РЕГЛАМЕНТУ, КОПИРУЙ ТРАССИРОВКУ С КОДОМ ИЗ ТЕРМИНАЛА

**Comment by ruslansenatorov** [comment]
invalid name. @VIVALDI142857
