### ISSUE TITLE
Unabe to parse command-line config 

### ISSUE THREAD

**Issue by callogan** [SENATOROVAI/pre-commit#3]
![image](https://github.com/user-attachments/assets/546996c0-3701-4159-a974-a065fcf122cc)
After I have downloaded new release 1.0.2 the following message occured - missing config value GIT_COFIG_VALUE_0, fatal: unable to parse command-line config.

**Comment by ruslansenatorov** [comment]
![image](https://github.com/user-attachments/assets/919aadd4-3cb0-4997-ace4-7054410c51da)

**Comment by ruslansenatorov** [comment]
pre-commit.log

**Comment by ruslansenatorov** [comment]
> ![image](https://private-user-images.githubusercontent.com/55090151/380451608-546996c0-3701-4159-a974-a065fcf122cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NzgwMTksIm5iZiI6MTcyOTk3NzcxOSwicGF0aCI6Ii81NTA5MDE1MS8zODA0NTE2MDgtNTQ2OTk2YzAtMzcwMS00MTU5LWE5NzQtYTA2NWZjZjEyMmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDIxMjE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNTcwZjA0OTQ2ZTI4YmNjZmRiMjgwMDg0YzU3MjdmOGRiNjMxNTdkYWMzYWMzNjFlNDI4ODNjZTM4NzMyN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h4MohgwqUTO7DHhHkhCjuXBunt8-nOj6KPtysJ_hFOs) After I have downloaded new release 1.0.2 the following message occured - missing config value GIT_COFIG_VALUE_0, fatal: unable to parse command-line config.

git config --list
git config --global user.name "Your Name"
git config --global user.email "your.email@example.com"
