### ISSUE TITLE
Jupytext

### ISSUE THREAD

**Issue by Zakieva** [SENATOROVAI/pre-commit#31]
### Feature description

![изображение](https://github.com/user-attachments/assets/00dd7be7-bc6b-488d-8287-21856dc62e4d)

**Comment by Zakieva** [comment]
PS C:\Users\Закиев Айнур\Documents\GitHub\Python-Kate> cd pre-commit
PS C:\Users\Закиев Айнур\Documents\GitHub\Python-Kate\pre-commit> git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 998 bytes | 38.00 KiB/s, done.
From https://github.com/SENATOROVAI/pre-commit
   bd28047..89c82c9  main       -> origin/main
Updating bd28047..89c82c9
Fast-forward
 .pre-commit-config.yaml | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
PS C:\Users\Закиев Айнур\Documents\GitHub\Python-Kate\pre-commit> cd
PS C:\Users\Закиев Айнур\Documents\GitHub\Python-Kate\pre-commit> pre-commit run --all-files
An error has occurred: InvalidConfigError: 
=====> .pre-commit-config.yaml is not a file
Check the log at C:\Users\Закиев Айнур\.cache\pre-commit\pre-commit.log
PS C:\Users\Закиев Айнур\Documents\GitHub\Python-Kate\pre-commit> cd.. 
PS C:\Users\Закиев Айнур\Documents\GitHub\Python-Kate> pre-commit run --all-files
[INFO] Initializing environment for https://github.com/mwouts/jupytext:black,isort.
[INFO] Installing environment for https://github.com/mwouts/jupytext.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Закиев Айнур\\.cache\\pre-commit\\repo8o9jwh6z\\py_env-python3.12\\Scripts\\python.EXE', '-mpip', 'install', '.', 'black', 'isort')
return code: 1
stdout:
    Processing c:\users\������ �����\.cache\pre-commit\repo8o9jwh6z
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      pip subprocess to install build dependencies did not run successfully.
      exit code: 1
      
      [101 lines of output]
      Collecting jupyter_packaging~=0.7.9
        Using cached jupyter_packaging-0.7.12-py2.py3-none-any.whl.metadata (996 bytes)
      Collecting jupyterlab==3.*,>=3.0.0
        Using cached jupyterlab-3.6.8-py3-none-any.whl.metadata (12 kB)
      Collecting setuptools>=40.8.0
        Using cached setuptools-75.3.0-py3-none-any.whl.metadata (6.9 kB)
      Collecting wheel
        Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
      Collecting ipython (from jupyterlab==3.*,>=3.0.0)
        Using cached ipython-8.29.0-py3-none-any.whl.metadata (5.0 kB)
      Collecting packaging (from jupyterlab==3.*,>=3.0.0)
        Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
      Collecting tornado>=6.1.0 (from jupyterlab==3.*,>=3.0.0)
        Using cached tornado-6.4.1-cp38-abi3-win_amd64.whl.metadata (2.6 kB)
      Collecting jupyter-core (from jupyterlab==3.*,>=3.0.0)
        Using cached jupyter_core-5.7.2-py3-none-any.whl.metadata (3.4 kB)
      Collecting jupyterlab-server~=2.19 (from jupyterlab==3.*,>=3.0.0)
        Using cached jupyterlab_server-2.27.3-py3-none-any.whl.metadata (5.9 kB)
      Collecting jupyter-server<3,>=1.16.0 (from jupyterlab==3.*,>=3.0.0)
        Using cached jupyter_server-2.14.2-py3-none-any.whl.metadata (8.4 kB)
      Collecting jupyter-ydoc~=0.2.4 (from jupyterlab==3.*,>=3.0.0)
        Using cached jupyter_ydoc-0.2.5-py3-none-any.whl.metadata (2.2 kB)
      Collecting jupyter-server-ydoc~=0.8.0 (from jupyterlab==3.*,>=3.0.0)
        Using cached jupyter_server_ydoc-0.8.0-py3-none-any.whl.metadata (5.3 kB)
      Collecting nbclassic (from jupyterlab==3.*,>=3.0.0)
        Using cached nbclassic-1.1.0-py3-none-any.whl.metadata (3.6 kB)
      Collecting notebook<7 (from jupyterlab==3.*,>=3.0.0)
        Using cached notebook-6.5.7-py3-none-any.whl.metadata (2.5 kB)
      Collecting jinja2>=2.1 (from jupyterlab==3.*,>=3.0.0)
        Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
      Collecting MarkupSafe>=2.0 (from jinja2>=2.1->jupyterlab==3.*,>=3.0.0)
        Using cached MarkupSafe-3.0.2-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
      Collecting anyio>=3.1.0 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached anyio-4.6.2.post1-py3-none-any.whl.metadata (4.7 kB)
      Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached argon2_cffi-23.1.0-py3-none-any.whl.metadata (5.2 kB)
      Collecting jupyter-client>=7.4.4 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached jupyter_client-8.6.3-py3-none-any.whl.metadata (8.3 kB)
      Collecting jupyter-events>=0.9.0 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached jupyter_events-0.10.0-py3-none-any.whl.metadata (5.9 kB)
      Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached jupyter_server_terminals-0.5.3-py3-none-any.whl.metadata (5.6 kB)
      Collecting nbconvert>=6.4.4 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached nbconvert-7.16.4-py3-none-any.whl.metadata (8.5 kB)
      Collecting nbformat>=5.3.0 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
      Collecting overrides>=5.0 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
      Collecting prometheus-client>=0.9 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached prometheus_client-0.21.0-py3-none-any.whl.metadata (1.8 kB)
      Collecting pywinpty>=2.0.1 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached pywinpty-2.0.14-cp312-none-win_amd64.whl.metadata (5.2 kB)
      Collecting pyzmq>=24 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached pyzmq-26.2.0-cp312-cp312-win_amd64.whl.metadata (6.2 kB)
      Collecting send2trash>=1.8.2 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached Send2Trash-1.8.3-py3-none-any.whl.metadata (4.0 kB)
      Collecting terminado>=0.8.3 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
      Collecting traitlets>=5.6.0 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached traitlets-5.14.3-py3-none-any.whl.metadata (10 kB)
      Collecting websocket-client>=1.7 (from jupyter-server<3,>=1.16.0->jupyterlab==3.*,>=3.0.0)
        Using cached websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
      Collecting platformdirs>=2.5 (from jupyter-core->jupyterlab==3.*,>=3.0.0)
        Using cached platformdirs-4.3.6-py3-none-any.whl.metadata (11 kB)
      Collecting pywin32>=300 (from jupyter-core->jupyterlab==3.*,>=3.0.0)
        Using cached pywin32-308-cp312-cp312-win_amd64.whl.metadata (8.3 kB)
      Collecting jupyter-server-fileid<1,>=0.6.0 (from jupyter-server-ydoc~=0.8.0->jupyterlab==3.*,>=3.0.0)
        Using cached jupyter_server_fileid-0.9.3-py3-none-any.whl.metadata (4.7 kB)
      Collecting ypy-websocket<0.9.0,>=0.8.2 (from jupyter-server-ydoc~=0.8.0->jupyterlab==3.*,>=3.0.0)
        Using cached ypy_websocket-0.8.4-py3-none-any.whl.metadata (2.5 kB)
      Collecting y-py<0.7.0,>=0.6.0 (from jupyter-ydoc~=0.2.4->jupyterlab==3.*,>=3.0.0)
        Using cached y_py-0.6.2.tar.gz (53 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1

        [6 lines of output]

        Cargo, the Rust package manager, is not installed or is not on PATH.
        This package requires Rust and Cargo to compile extensions. Install it through
        the system's package manager or via https://rustup.rs/

        Checking for Rust toolchain....
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error

    pip subprocess to install build dependencies did not run successfully.
    exit code: 1

    See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
Check the log at C:\Users\Закиев Айнур\.cache\pre-commit\pre-commit.log
PS C:\Users\Закиев Айнур\Documents\GitHub\Python-Kate>

**Comment by ruslansenatorov** [comment]
Closes 4b34c0733f3c3d2f15e66001b9b25e93e78ef656
