### ISSUE TITLE
Flake8, W293: blank line contains whitespace. Linter. Github actions

### ISSUE THREAD

**Issue by Umekko** [SENATOROVAI/pre-commit#41]
### Feature description

![image](https://github.com/user-attachments/assets/5c43d719-decc-4e46-a7a3-cafd827ae40a)

**Comment by ruslansenatorov** [comment]
closes https://github.com/SENATOROVAI/pre-commit/commit/bcdaecb5b48f51b4e6f165ded59af57a4e6da4aa
