### ISSUE TITLE
[BUG] AttributeError: 'zipimporter' object has no attribute 'find_module'. Did you mean: 'load_modulee'?

### ISSUE THREAD

**Issue by slyciaqe** [SENATOROVAI/pre-commit#49]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://t.me/c/1937296927/3602/25534) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) or [chatGPT](https://t.me/c/1937296927/2415/23729) and didn't find any helpful information.

### Attach a full screenshot and write what did you do to fix the problem?

![385695806-435833f4-2834-4d60-a1f2-a3bd2fddd8f8](https://github.com/user-attachments/assets/0b16ef18-63ba-4f3d-a596-29d96e8b42ff)

### Error from the terminal / Code

AttributeError: 'zipimporter' object has no attribute 'find_module'. Did you mean: 'load_module'?

### Expected behavior

linter is working without mistakes

### Actual behavior

1. open terminal in VsCode
2.  run comand - pre-commit run --all-files

**Comment by ruslansenatorov** [comment]
Closes https://github.com/SENATOROVAI/pre-commit/pull/48
