### ISSUE TITLE
Pre-commit folder adding to git issue

### ISSUE THREAD

**Issue by callogan** [SENATOROVAI/pre-commit#9]
### What would you like to share?

After I have commited the latest release v. 1.0.3 I saw that I still have uncommited folder "pre-commit" in the root of my local repository. While I tried to add it to git via "git add ." comand for futher commit it showed the warning you can see on the Screenshot attached. In this case I don't exactly know what I should do: add it as submodule or remove from ubtracked files or just delete (last option I can't do without administrator role which is difficult to get in my case).
![pre_commit_ifolder_issue](https://github.com/user-attachments/assets/8c35ca78-6e48-402b-bc6b-18f15a93a1ce)

**Comment by ruslansenatorov** [comment]
Delete colder

**Comment by ruslansenatorov** [comment]
delete folder

**Comment by ruslansenatorov** [comment]
Not delete folder
